### PR TITLE
Fixes for unique_together, caching and autofield

### PR DESCRIPTION
**Pull request by em1208**
Hello,

I created this PR to remove incompatibilities with the recent version of Django (5.1).

I hope this can be merged and released.

Thanks!

### CODE REVIEW

**Comment by em1208** [comment]
@jorenham  I understand this project is abandoned, but would it be possible to transfer it to another maintainer? Thanks!

**Comment by jorenham** [comment]
That would, at the very least, require the current maintainer to respond to issues or other attempts to contact him/her. But that hasn't happened so far.

**Comment by em1208** [comment]
@jorenham Thanks for your reply! If that's the case I will create my own fork and release it in pypi under another name.

**Comment by jorenham** [comment]
@em1208 you could also use [my fork](https://github.com/jorenham/django-cron), which includes a similar fix for this issue.

**Comment by em1208** [comment]
@jorenham Is your fork available on pypi? If not are you able to release it?

**Comment by jorenham** [comment]
it isn't, but you can install it with e.g. pip (and most other package managers) either way:

```shell
pip install git+https://github.com/jorenham/django-cron.git
```

**Comment by em1208** [comment]
Thanks, pip install via git works but doesn't handle well the caching of requirements so, ideally, would be nice to have the version released on pypi with a specific version number. Thanks a lot again!

**Pull request closed without merging**
